
export const CHECK_AUTHENTICATED_ACTION = 'CHECK_AUTHENTICATED_ACTION'

export const SET_AUTHENTICATED_ACTION = 'SET_AUTHENTICATED_ACTION'

export const LOGIN_ACTION = 'LOGIN_ACTION'

export const LOGOUT_ACTION = 'LOGOUT_ACTION'
